# Prints the configuration options and their values in an aligned column.
function (print_summary)
    # The widest option name determines the column width.
    set (_width 0)
    foreach (_opt ${ARGN})
        string (LENGTH ${_opt} _len)
        if (_len GREATER _width)
            set (_width ${_len})
        endif ()
    endforeach ()
    message (STATUS "Summary:")
    foreach (_opt ${ARGN})
        string (LENGTH ${_opt} _len)
        math (EXPR _pad "${_width} - ${_len}")
        set (_gap "")
        if (_pad GREATER 0)
            string (REPEAT " " ${_pad} _gap)
        endif ()
        if (${_opt})
            set (_val ON)
        else ()
            set (_val OFF)
        endif ()
        message (STATUS "  ${_opt}${_gap} : ${_val}")
    endforeach ()
endfunction ()
